# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserIofo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('dp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Depart')),
            ],
        ),
    ]
