# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default=666, max_length=64),
            preserve_default=False,
        ),
    ]
