# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-05 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=64)),
                ('port', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('services', models.ManyToManyField(to='my_mamager.ServiceLine')),
            ],
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='service_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_mamager.ServiceLine'),
        ),
    ]
