# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20171114_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_group',
            field=models.BooleanField(default=1, verbose_name='是否是组'),
            preserve_default=False,
        ),
    ]
