# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='tomcat',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
