# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
