# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfo',
            old_name='service_line',
            new_name='userhost',
        ),
    ]
