# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_app', '0002_auto_20170912_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='ip',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='port',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userhost',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
