# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserecord',
            old_name='course',
            new_name='class_obj',
        ),
    ]
