# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20171031_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='survery',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='创建者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='班级'),
        ),
    ]
