# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20171031_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surverychoices',
            name='content',
            field=models.CharField(max_length=256, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='surveryitem',
            name='answer_type',
            field=models.IntegerField(choices=[(1, '单选'), (2, '打分'), (3, '建议')], default=1, verbose_name='问题类型'),
        ),
        migrations.AlterField(
            model_name='surveryitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='调查问题'),
        ),
    ]
