# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20171101_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surverychoices',
            old_name='question',
            new_name='item',
        ),
    ]
