# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoftWare',
            new_name='Tomcat',
        ),
    ]
