# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_tomcat_tomcat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomcat',
            name='tomcat_name',
            field=models.CharField(max_length=64),
        ),
    ]
