# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='APP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=64)),
                ('domain_name', models.CharField(blank=True, max_length=64)),
                ('project_path', models.CharField(blank=True, max_length=64)),
                ('app_path', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '应用详细表',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '应用名称表',
            },
        ),
        migrations.RemoveField(
            model_name='tomcat',
            name='host',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='name',
            new_name='hostname',
        ),
        migrations.DeleteModel(
            name='Tomcat',
        ),
        migrations.AddField(
            model_name='app',
            name='host',
            field=models.ManyToManyField(blank=True, to='project_app.Host', verbose_name='所在主机'),
        ),
        migrations.AddField(
            model_name='app',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Application', verbose_name='应用名称'),
        ),
    ]
