# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_auto_20171122_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysTem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': '系统版本',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='system',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='project_app.SysTem', verbose_name='系统'),
            preserve_default=False,
        ),
    ]
