# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_auto_20171122_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='app_name',
            field=models.ManyToManyField(blank=True, to='project_app.Application', verbose_name='应用'),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
