# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_auto_20171122_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='host_ip',
            field=models.ManyToManyField(blank=True, to='project_app.Host', verbose_name='主机'),
        ),
    ]
