# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0009_application_host_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='app_name',
        ),
    ]
