# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0010_remove_host_app_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='host_ip',
        ),
    ]
