# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('type_id', models.SmallIntegerField(choices=[(1, 'URL'), (2, 'Action')], default=1)),
                ('code', models.CharField(max_length=32, verbose_name='代码')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Permission', verbose_name='权限')),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='代码')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Action', verbose_name='Action')),
                ('role_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Role2Permission', verbose_name='权限')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='useraction',
            unique_together=set([('action', 'role_permission')]),
        ),
    ]
