# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20171030_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role2Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Action')),
            ],
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='pre_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='permission',
            name='caption',
            field=models.CharField(max_length=32, verbose_name='权限名称'),
        ),
        migrations.AddField(
            model_name='role2permission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rs', to='rbac.Permission'),
        ),
        migrations.AddField(
            model_name='role2permission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pers', to='rbac.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='role2permission',
            unique_together=set([('role', 'permission', 'action')]),
        ),
    ]
