# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20171030_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='type_id',
        ),
    ]
