# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_auto_20171030_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissioncode',
            name='code',
            field=models.CharField(max_length=16, unique=True, verbose_name='代码'),
        ),
    ]
