# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_auto_20171030_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=128, unique=True, verbose_name='URL'),
        ),
    ]
