# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0014_auto_20171030_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='权限代码'),
        ),
    ]
