# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0016_auto_20171030_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_menu',
        ),
    ]
