# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0018_auto_20171031_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='拥有权限'),
        ),
    ]
