# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0019_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=64, verbose_name='权限代码'),
        ),
    ]
