# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0020_auto_20171031_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='URL'),
        ),
    ]
