# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0022_permission_is_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='menu',
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rbac.Menu', verbose_name='所属组'),
            preserve_default=False,
        ),
    ]
